projet/communitymanager/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('newsfeed/', views.newsfeed, name='newsfeed'),
    path('communautes/', views.communautes, name='communautes'),
    path('', views.communautes),
    path('desabonnement/<int:com_id>', views.desabonnement, name='desabonnement'),
    path('abonnement/<int:com_id>', views.abonnement, name='abonnement'),
    path('communaute/<int:com_id>', views.communaute, name='communaute'),
    path('post/<int:post_id>', views.post, name='post'),
    path('nouveau_post/', views.nouveau_post, name='nouveau-post'),
    path('modif_post/<int:post_id>', views.modif_post, name='modif-post'),
    path('suppress_post/<int:post_id>', views.suppress_post, name='suppress-post'),
    path('voir_commentaires/<int:post_id>', views.voir_commentaires, name='voir-commentaires'),
]

projet/projet/urls.py
from django.contrib import admin
from django.urls import path, include
from communitymanager import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('communitymanager.urls')),
]

projet/communitymanager/models.py
from django.db import models
from django.contrib.auth.models import User


class Communaute(models.Model):
    nom = models.CharField(max_length=40)
    abonnes = models.ManyToManyField(User)

    def __str__(self):
        return self.nom


class Priorite(models.Model):
    label = models.CharField(max_length=20)

    def __str__(self):
        return self.label


class Post(models.Model):
    titre = models.CharField(max_length=30)
    description = models.TextField()
    date_creation = models.DateTimeField()
    communaute = models.ForeignKey(Communaute, on_delete=models.CASCADE)
    priorite = models.ForeignKey(Priorite, on_delete=models.CASCADE)
    evenementiel = models.BooleanField()
    date_evenement = models.DateTimeField(blank=True, null=True)
    auteur = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.titre


class Commentaire(models.Model):
    date_creation = models.DateTimeField()
    contenu = models.CharField(max_length=300)
    auteur = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

projet/communitymanager/forms.py
from django import forms
from .models import Post
from .models import Commentaire


class ConnexionForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)


class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('date_creation', 'auteur', 'evenementiel', 'date_evenement')

    def clean_evenement_date(self, request):
        #Le format de la date n'est désormais plus le bon et il faut donc le remettre au bon format pour qu'il
        # soit accepté lors de la sauvegarde de l'objet
        if request.POST.get('evenementiel'):
            evenementiel = True
            date = request.POST.get('date_evenement')
            date_evenement = ""
            for i in range(len(date)):
                if date[i] == 'T':
                    date_evenement += ' '
                else:
                    date_evenement += date[i]
            return evenementiel, date_evenement
        else:
            return False, None



class NewCommentForm(forms.ModelForm):
    class Meta:
        model = Commentaire
        fields = ('contenu',)

projet/communitymanager/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Communaute
from .models import Post
from .models import Commentaire
from .models import Priorite
from .forms import NewPostForm
from .forms import NewCommentForm
from datetime import datetime


@login_required()
def newsfeed(request):
    """
    Renvoie l'ensemble des posts dont la communauté appartient à la liste des communautés de l'utilisateur
    """
    communautes = request.user.communaute_set.all()
    list = Post.objects.filter(Q(communaute__in=communautes)).order_by('date_creation').reverse()
    return render(request, 'communitymanager/newsfeed.html', locals())


def disconnect(request):
    return redirect('accounts/logout')


@login_required()
def communautes(request):
    list = Communaute.objects.all()
    return render(request, 'communitymanager/communaute-list.html', locals())


@login_required()
def desabonnement(request, com_id):
    c = Communaute.objects.get(id=com_id)
    c.abonnes.remove(request.user)
    return redirect('communautes')


@login_required()
def abonnement(request, com_id):
    c = Communaute.objects.get(id=com_id)
    c.abonnes.add(request.user)
    return redirect('communautes')


@login_required()
def communaute(request, com_id):
    list = Post.objects.filter(communaute=Communaute.objects.get(id=com_id))
    com = Communaute.objects.get(id=com_id)
    return render(request, 'communitymanager/communaute.html', locals())


@login_required()
def post(request, post_id):
    post = Post.objects.get(id=post_id)
    comments = Commentaire.objects.filter(post=post)
    form = NewCommentForm(request.POST or None)
    if form.is_valid():
        #On n'enregistre pas directement le form car certains éléments automatiques doivent être ajoutés au form
        commentaire = form.save(commit=False)
        commentaire.date_creation = datetime.now()
        commentaire.auteur = request.user
        commentaire.post = post
        commentaire.save()
        return redirect('post', post_id)
    return render(request, 'communitymanager/post-details.html', locals())


@login_required()
def nouveau_post(request):
    form = NewPostForm(request.POST or None)
    prio = Priorite.objects.all()
    communautes = request.user.communaute_set.all()
    if form.is_valid():
        post = form.save(commit=False)

        #On récupère ces deux éléments sous une forme de date pour pouvoir enregistrer le post
        post.evenementiel, post.date_evenement = form.clean_evenement_date(request)
        post.date_creation = datetime.now()
        post.auteur = request.user
        post.save()
        return redirect('communaute', com_id=post.communaute.id)
    #Si le form n'est pas valide on renvoie la vue de création de post
    return render(request, 'communitymanager/post-creation.html', locals())


@login_required()
def modif_post(request, post_id):
    #On commence par récupérer le post d'origine pour pouvoir rentrer ses valeurs dans le form
    p = get_object_or_404(Post, id=post_id)

    #Si l'utilisateur en est bien l'auteur alors il a le droit de le modifier
    if p.auteur == request.user:
        form = NewPostForm(request.POST or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.auteur = request.user
            #La date de création est mise à jour à la date de la modification
            post.date_creation = datetime.now()
            return redirect('post', post_id=post_id)
        else:
            form = NewPostForm(instance=p)
            return render(request, 'communitymanager/modify-post.html', locals())
    else :
        #Si jamais l'utilisateur n'est pas l'auteur on doit récupérer l'ensemble des posts et ajouter une variable pour
        # pouvoir afficher un message d'erreur
        list = Post.objects.filter(communaute=Communaute.objects.get(id=Post.objects.get(id=post_id).communaute.id))
        can_modif = True
        return render(request, 'communitymanager/communaute.html', locals())


@login_required()
def suppress_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    #Seul l'auteur du post peut le supprimer
    if post.auteur == request.user:
        com_id = post.communaute.id
        post.delete()
        return redirect('communaute', com_id=com_id)
    else :
        list = Post.objects.filter(communaute=Communaute.objects.get(id=Post.objects.get(id=post_id).communaute.id))
        can_suppress = True
        return render(request, 'communitymanager/communaute.html', locals())


@login_required()
def voir_commentaires(request, post_id):
    """
    Cette méthode est appelée quand un utilisateur sur la page newsfeed veut voir les commentaires d'un
    post en particulier
    """
    post = Post.objects.get(id=post_id)
    commentaires = Commentaire.objects.filter(post=post)
    voir_comm = True
    communautes = request.user.communaute_set.all()
    list = Post.objects.filter(Q(communaute__in=communautes)).order_by('date_creation').reverse()
    return render(request, 'communitymanager/newsfeed.html', locals())

projet/communitymanager/templates/communitymanager/communaute-list.html
<head>
    <title>Liste des communautés</title>
</head>
{% extends 'base.html' %}

{% block titre %}
<h1>L'ensemble de nos communautés</h1>
{% endblock %}

<!-- Il est nécessaire de réécrire le block menu car l'un des onglets est désormais actif -->
{% block menu %}
<ul class="col-12 nav nav-tabs nav-justified">

    <li class="nav-item">
      <a class="nav-link" href="../newsfeed">Newsfeed</a>
    </li>

    <li class="nav-item">
      <a class="nav-link active" href="../communautes">Communautés</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="../nouveau_post">Créer un post</a>
    </li>

</ul>
{% endblock %}




{% block content %}
<table class="table col-4 text-center" style="font-size:20px; margin:auto;">

  {% for com in list %}
  <tr>
    <td><a href="{% url 'communaute' com.id %}">{{ com.nom }}</a></td>

      <!-- L'affichage du coeur dépend de si l'utilisateur est abonné ou non -->
    {% if user in com.abonnes.all %}
    <td><a href="{% url 'desabonnement' com.id %}" style="text-decoration: None;color:red;"><i class="fas fa-heart" style="color:red;"></i></a></td>
    {% else %}
    <td><a href="{% url 'abonnement' com.id %}" style="text-decoration: None;color:black;"><i class="far fa-heart" style="color:red;"></i></a></td>
    {% endif %}

  </tr>
  {% endfor %}

</table>
{% endblock %}

projet/communitymanager/templates/communitymanager/communaute.html
<head>
    <title>Communauté</title>
</head>

{% extends "base.html" %}

{% block titre %}
<h1>Posts de la communauté {{ com.nom }}</h1>
{% endblock %}

{% block content %}

{% if can_modif %}
<p style="color:red;">Vous ne pouvez pas modifier ce post car vous n'en êtes pas l'auteur.</p>
{% elif can_suppress %}
<p style="color:red;">Vous ne pouvez pas supprimer ce post car vous n'en êtes pas l'auteur.</p>
{% endif %}

<!-- Affichage des posts un à un de la liste fournie (dont la communauté est celle correspondant à l'identifiant) -->
{% for post in list %}
<div class="post col-11">
    <p class="col-push-6 text-right">{{ post.date_creation }}</p>
    <p class="col-8"><a class="titrepost" href="{% url 'post' post.id %}">{{ post.titre }}</a> par {{ post.auteur }}</p>
    <p class="col-8">{{ post.description }}</p>
    <p class="text-center col-11"><a href="{% url 'modif-post' post.id %}" style="margin-right:10%">Modifier</a><a href="{%url 'suppress-post' post.id %}"><i class="fas fa-times"></i></a></p>

</div>
{% endfor %}

{% endblock %}

projet/communitymanager/templates/communitymanager/modify-post.html
<head>
    <title>Modifier un post</title>
</head>

{% extends 'base.html' %}

{% block titre %}
<h1>Modification d'un post</h1>
{% endblock %}

{% block content %}

<p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit"/>
  </form>
</p>

{% endblock %}

projet/communitymanager/templates/communitymanager/newsfeed.html
<head>
    <title>Newsfeed</title>
</head>

{% extends 'base.html' %}

{% block titre %}
<h1>Newsfeed</h1>
{% endblock %}

<!-- Il est nécessaire de réécrire le block menu car l'un des onglets est désormais actif -->
{% block menu %}
<ul class="col-12 nav nav-tabs nav-justified">

    <li class="nav-item">
      <a class="nav-link active" href="../newsfeed">Newsfeed</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="../communautes">Communautés</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="../nouveau_post">Créer un post</a>
    </li>

</ul>
{% endblock %}

{% block content %}

{% for post in list %}

<div class="post col-11">

    <p class="col-push-9 text-right">{{ post.date_creation }}</p>
    <p class="col-8"><a class="titrepost" href="{% url 'post' post.id %}">{{ post.titre }}</a> par {{ post.auteur }}</p>
    <p class="col-8">{{ post.description }}</p>

    <!-- Si l'on a demandé à voir les commentaires de ce post en particulier... -->
    {% if voir_comm and post.id == post_id %}
    <a href="{% url 'newsfeed' %}">Masquer les commentaires</a>
    <div class="comment col-10">

        <!-- Alors on affiche chacun d'entre eux en dessous du post -->
        {% for comment in commentaires %}
        <p style="margin-bottom:0%; font-weight: bold">{{ comment.auteur }} le {{ post.date_creation }}</p>
        <p style="margin-left:5%">{{ comment.contenu }}</p>
        {% endfor %}

    </div>
    {% else %}
    <a href="{% url 'voir-commentaires' post.id %}">Afficher les commentaires</a>
    {% endif %}

</div>
{% endfor %}

{% endblock %}

projet/communitymanager/templates/communitymanager/post-creation.html
<head>
    <title>Créer un post</title>
</head>

{% extends 'base.html' %}

{% block titre %}
<h1>Nouveau post</h1>
{% endblock %}

<!-- Il est nécessaire de réécrire le block menu car l'un des onglets est désormais actif -->
{% block menu %}

<ul class="col-12 nav nav-tabs nav-justified">

    <li class="nav-item">
        <a class="nav-link" href="../newsfeed">Newsfeed</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="../communautes">Communautés</a>
    </li>

    <li class="nav-item">
        <a class="nav-link active" href="../nouveau_post">Créer un post</a>
    </li>

</ul>

{% endblock %}

<!-- Ici j'ai essayé de faire un affichage pour le form en utilisant Bootstrap ce qui rend l'ensemble très lourd -->
{% block content %}

<div class="container-fluid">

    <form class="col-6" style="margin:auto;" method="post" action=".">
    {% csrf_token %}

        <div class="form-inline" style="margin:5%">
            <label for="id_communaute">Communaute </label>
            <select class="form-control" id="id_communaute" name="communaute" required>
                <option></option>
                {% for commu in communautes %}
                <option value="{{ commu.id }}">{{ commu }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-inline" style="margin: 5%">
            <label class="mr-sm-2" for="id_titre">Titre </label>
            <input type="text" class="form-control" id="id_titre" name="titre" required/>
        </div>

        <div class="form-inline" style="margin: 5%">
            <label class="mr-sm-2" for="id_description">Description </label>
            <textarea class="form-control" rows="5" cols="50" id="id_description" name="description" required></textarea>
        </div>
        <div class="form-inline" style="margin: 5%">
            <label for="id_evenementiel">Est-ce une événement ? </label>
            <input type="checkbox" class="a" id="id_evenementiel" name="evenementiel"/>
        </div>

        <div class="form-inline" style="margin: 5%">
            {% if trop_tot %}
            <p style="color:red">La date est invalide</p>
            {% endif %}
            <label class="mr-sm-2" for="id_date_evenement">Date de l'événement </label>
            <input type="datetime-local" id="id_date_evenement" name="date_evenement"/>
        </div>

        <div class="form-inline" style="margin: 5%">
            <label class="mr-sm-2" for="id_priorite">Priorité </label>
            <select class="form-control" id="id_priorite" name="priorite" required>
                {% for priorite in prio %}
                <option value="{{ priorite.id }}">{{ priorite }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="text-center">
            <input type="submit" value="Envoyer" style="margin:5%">
        </div>

    </form>
</div>

{% endblock %}

projet/communitymanager/templates/communitymanager/post-details.html
<head>
    <title>Détails d'un post</title>
</head>

{% extends 'base.html' %}

{% block titre %}
<h1>Post de la communauté {{ post.communaute.nom }}</h1>
{% endblock %}

{% block content %}

<div class="post">
    <p class="col-8"><span class="titrepost">{{ post.titre }}</span> par {{ post.auteur }}</p>

    <!-- Affiche les informations du post -->
    <p>
      {{ post.description }}</br>
      {% if post.evenementiel %}
      Date de l'événement : {{post.date_evenement}}</br>
      {% endif %}
    </p>

    <!-- Affiche les commentaires de ce post -->
    <p style="font-weight: bold">Commentaires :</p>
        <div class="comment">
        {% for comment in comments %}
        <p style="font-weight: bold">{{ comment.auteur }} le {{comment.date_creation}}</p>
            <p style="margin-left: 5%">{{ comment.contenu }}</p>
        {% endfor %}
        </div>
    </p>

    <!-- Permet l'ajout de nouveaux commentaires -->
    <p>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"/>
      </form>
    </p>
</div>

{% endblock %}

projet/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


</head>
<body>

<div class="jumbotron head">

    <div class="container-fluid">
        <div class="col-12 text-center titre">
        {% block titre %}
        {% endblock %}
        </div>
        <div class="row align-right">
            {% block disconnect %}
            <div class="col-11"></div>
            <a class="col-1" href="{% url 'logout' %}" style="padding:3%"><img src="/static/image/disconnect.png" alt="Déconnexion" style="width:100%"/></a>
            {% endblock %}
        </div>
        {% block menu %}
        <ul class="col-12 nav nav-tabs nav-justified">
            <li class="nav-item">
              <a class="nav-link" href="../newsfeed">Newsfeed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../communautes">Communautés</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../nouveau_post">Créer un post</a>
            </li>
        </ul>
        {% endblock %}
    </div>
</div>

{% block content %}
{% endblock %}
</body>
</html>